config/routes.rb
Rails.application.routes.draw do
	
  
  resources :queries do
    member do
      get :update_status
      get :set_creator
      get :archive
    end
  end

  resources :subjects do
    resources :lessons, path: ''
  end

  resources :profiles
  devise_for :users, controllers: { registrations: 'users/registrations' } 
  get 'contact' , to: "pages#contact"
  get 'portal' , to: "pages#portal"
  get 'my-profile', to: "pages#myprofile"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue btm">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
  	   <%= @copyright%> 
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navigation.html.erb
<div class="container">
<nav class="navbar  navbar-light bg-transparent">
 <a class="navbar-brand" href="/">FAZH</a>
 <form class="form-inline">
    <%= link_to "Subjects", subjects_path, :class => "nav-link" %> 
    <%= link_to "Portal", portal_path, :class => "nav-link"   if logged_in?(:tutor) | logged_in?(:root_admin) %>

    <%= link_to "My Profile" , my_profile_path, :class => "nav-link" if current_user %>
  	<%= link_to "Contact" , contact_path, :class => "nav-link"%>
    <%= link_to "Login" , new_user_session_path, :class => "btn btn-outline-primary"  if !current_user %>
  <div style="padding-left: 10px;">
      <%= link_to "Sign Up" , new_user_registration_path, :class => "btn btn-outline-success" if !current_user  %>
      <%= link_to "Logout" , destroy_user_session_path, method: :delete, :class => "btn btn-outline-success"  if current_user %>
  </div>
  </form>
  </nav>
</div>
<hr>
 <%= link_to "Submit Question", new_query_path  if logged_in?(:student) %>

app/views/shared/_qstatus.html.erb
    <%if query.active? %>
    <%= link_to query.status, update_status_query_path(query) if logged_in?(:tutor) | logged_in?(:root_admin)%>
    <%= query.status if logged_in?(:student) %>
    <% elsif query.accepted? %>
    <%= link_to 'Give_up', update_status_query_path(query) if query.profile_id == @current_user.profile_id %>
    <%= "Taken".html_safe if query.profile_id != @current_user.profile_id %>
    <% elsif query.submitted? %>
    <%= link_to "Archive", archive_query_path(query) %>
    <% elsif query.archived? %>
    <%= query.status if logged_in?(:root_admin) %>
    <% end %>

app/views/shared/_set_subject_name.html.erb
<h1><%= Subject.friendly.find(params[:subject_id]).title %></h1>