config/routes.rb
Rails.application.routes.draw do
	
  
  resources :queries do
    member do
      get :update_status
      get :set_creator
      get :archive
    end
  end

  resources :subjects do
    resources :lessons, path: ''
  end

  resources :profiles
  devise_for :users, controllers: { registrations: 'users/registrations' } 
  get 'contact' , to: "pages#contact"
  get 'portal' , to: "pages#portal"
  get 'my-profile', to: "pages#myprofile"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
end

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/myprofile.html.erb
<h1>My Profile</h1>

<p> Name: <%= current_user.profile.name %></p>
<p> <%= link_to 'Edit', edit_profile_path(current_user.profile) %></p>

<table>
  <thead>
    <tr>
      <th>Paper</th>
      <th>Level</th>
      <th>Year</th>
      <th>Session</th>
      <th>Board</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @queries.each do |query| %>
      <tr>
        <td><%= query.paper %></td>
        <td><%= query.level %></td>
        <td><%= query.year %></td>
        <td><%= query.session %></td>
        <td><%= query.board %></td>
        <td><%= query.description %></td>
        <td><%= query.image %></td>
        <td><%= link_to 'Show', query if logged_in?(:tutor) %></td> 
        <td><%= link_to 'Edit', edit_query_path(query) if logged_in?(:tutor) %></td>
        <td><%=  render 'shared/qstatus', query: query %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pages/portal.html.erb
<h1> Portal </h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Paper</th>
      <th>Level</th>
      <th>Year</th>
      <th>Session</th>
      <th>Board</th>
      <th>Description</th>
      <th>Owner</th>
      <th colspan="1"></th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @queries.each do |query| %>
      <tr>
        <% if query.active? %>
        <td><%= query.subject.title%></td>
        <td><%= query.paper %></td>
        <td><%= query.level %></td>
        <td><%= query.year %></td>
        <td><%= query.session %></td>
        <td><%= query.board %></td>
        <td><%= query.description %></td>
        <td><%= query.profile.name %></td>
        <td><%= link_to 'Show', query %></td>
        <td><%=  render 'shared/qstatus', query: query %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>

<br>