config/routes.rb
Rails.application.routes.draw do
	
  
  resources :queries do
    member do
      get :update_status
      get :set_creator
      get :archive
    end
  end

  resources :subjects do
    resources :lessons, path: ''
  end

  resources :profiles
  devise_for :users, controllers: { registrations: 'users/registrations' } 
  get 'contact' , to: "pages#contact"
  get 'portal' , to: "pages#portal"
  get 'my-profile', to: "pages#myprofile"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    extend FriendlyId

  belongs_to :subject
  mount_uploader :video, VideoUploader
  friendly_id :subject_link, use: :slugged

  include SubjectParameterize
  include GenNewFriendly
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], tutor: [:index, :new, :show, :edit, :create, :update, :destroy, :set_lesson, :lesson_params]
  # GET /lessons
  def index
   @lessons = Subject.friendly.find(params[:subject_id]).lessons
  end

  # GET /lessons/1
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  def create
    @lesson = Lesson.new(lesson_params)

    if @lesson.save
      redirect_to @lesson, notice: 'Lesson was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lessons/1
  def update
    if @lesson.update(lesson_params)
      redirect_to @lesson, notice: 'Lesson was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /lessons/1
  def destroy
    @lesson.destroy
    redirect_to lessons_url, notice: 'Lesson was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lesson_params
      params.require(:lesson).permit(:subject_id, :paper, :level, :year, :session, :board, :description, :video)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div>
    <label for="subject_id">Select Subject:</label>
    <%= form.collection_select :subject_id, Subject.all, :id, :title, prompt: true%>
  </div>


  <div class="field">
    <%= form.label :paper %>
    <%= form.number_field :paper %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :session %>
    <%= form.text_field :session %>
  </div>

  <div class="field">
    <%= form.label :board %>
    <%= form.text_field :board %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.file_field :video %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

 <%= render "shared/set_subject_name" %>
 <% @lessons.each do |less| %>
  <p><%= link_to 'Video' ,subject_lesson_path(id: less.id) %> </p>
  <hr>
<% end  %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @lesson.subject_id %>
</p>

<p>
  <strong>Paper:</strong>
  <%= @lesson.paper %>
</p>

<p>
  <strong>Level:</strong>
  <%= @lesson.level %>
</p>

<p>
  <strong>Year:</strong>
  <%= @lesson.year %>
</p>

<p>
  <strong>Session:</strong>
  <%= @lesson.session %>
</p>

<p>
  <strong>Board:</strong>
  <%= @lesson.board %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lesson.description %>
</p>

<p>
  <strong>Video:</strong>
 <%= video_player src: {mp4: @lesson.video.url} , setup: "{}", controls: true, width:"600" %>
</p>

<%=  link_to 'Edit', edit_lesson_path(@lesson) if logged_in?(:tutor)%> 
<%= link_to 'Back', subjects_path %>