config/routes.rb
Rails.application.routes.draw do
	
  
  resources :queries do
    member do
      get :update_status
      get :set_creator
      get :archive
    end
  end

  resources :subjects do
    resources :lessons, path: ''
  end

  resources :profiles
  devise_for :users, controllers: { registrations: 'users/registrations' } 
  get 'contact' , to: "pages#contact"
  get 'portal' , to: "pages#portal"
  get 'my-profile', to: "pages#myprofile"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
end

app/models/query.rb
class Query < ApplicationRecord
	extend FriendlyId
	validates_presence_of :image
	validates_presence_of :profile

	enum status:{active: 0, accepted: 1, archived: 2, submitted: 3}
	
	belongs_to :subject
	belongs_to :profile
	
	mount_uploader :image, ImageUploader
    friendly_id :subject_link, use: :slugged

    include SubjectParameterize
    include GenNewFriendly
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :set_query, only: [ :show, :edit, :update, :destroy, :update_status, :set_creator, :archive]
  access  student: [:new,:create, {except: [:show, :edit, :update,  :destroy, :set_query, :query_params]}], tutor: [:archive, :update_status,:show, :index, :edit, :update, :destroy, :set_query, :query_params]

  # GET /queries
  # Queries index is in pages and is called Portal
  # GET /queries/1
  # Creator is different Owner
  def index
    @queries = Query.where(status: "archived")
  end

  def show
    @creator = Profile.find(@query.creator)
  end


  # GET /queries/new
  def new
    @query = Query.new
    @query.build_subject
    @query.build_profile
  end

  # GET /queries/1/edit
  def edit
  end

  def update_status
    if @query.active?
      @query.accepted!
      @query.update(profile_id: current_user.profile_id)
    
  elsif @query.profile_id == @current_user.profile_id
    @query.active!
    @query.update(profile_id: @query.creator)
  end
    redirect_to my_profile_path
  end

  def archive

    if @query.submitted?
    @query.archived!
    @query.update(profile_id: 13)
    redirect_to my_profile_path
  else 
    @query.submitted!
    redirect_to new_lesson_path
  end
  end

  # POST /queries
  def create
    @query = Query.new(query_params)
    @query.profile_id = current_user.profile_id
    @query.creator = @current_user.profile_id
  
    if @query.save
      redirect_to my_profile_path, notice: 'Query was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /queries/1
  def update
    if @query.update(query_params)
      redirect_to @query, notice: 'Query was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /queries/1
  def destroy
    @query.destroy
    redirect_to portal_path, notice: 'Query was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_query
      @query = Query.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def query_params
      params.require(:query).permit(:paper, :level, :year, :session, :board, :description, :image, :subject_id, :profile_id)
    end
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/_form.html.erb
<%= form_with(model: query, local: true) do |form| %>
  <% if query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(query.errors.count, "error") %> prohibited this query from being saved:</h2>

      <ul>
        <% query.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div>
    <label for="subject_id">Select Subject:</label>
    <%= form.collection_select :subject_id, Subject.all, :id, :title, prompt: true%>
  </div>

  <div class="field">
    <%= form.label :paper %>
    <%= form.number_field :paper %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :session %>
    <%= form.text_field :session %>
  </div>

  <div class="field">
    <%= form.label :board %>
    <%= form.text_field :board %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/queries/edit.html.erb
<h1>Editing Query</h1>

<%= render 'form', query: @query %>

<%= link_to 'Show', @query %> |
<%= link_to 'Back', portal_path %>

app/views/queries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Archive</h1>

<table>
  <thead>
    <tr>
      <th>Paper</th>
      <th>Level</th>
      <th>Year</th>
      <th>Session</th>
      <th>Board</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @queries.each do |query| %>
      <tr>
        <td><%= query.paper %></td>
        <td><%= query.level %></td>
        <td><%= query.year %></td>
        <td><%= query.session %></td>
        <td><%= query.board %></td>
        <td><%= query.description %></td>
        <td><%= query.image %></td>
        <td><%= link_to 'Show', query %></td>
        <td><%= link_to 'Edit', edit_query_path(query) %></td>
        <td><%= link_to 'Destroy', query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Query', new_query_path %>

app/views/queries/new.html.erb
<h1>New Query</h1>

<%= render 'form', query: @query %>

<%= link_to 'Back', queries_path %>

app/views/queries/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Subject:</strong>
  <%= @query.subject.title %>
</p>

<p>
  <strong>Paper:</strong>
  <%= @query.paper %>
</p>

<p>
  <strong>Level:</strong>
  <%= @query.level %>
</p>

<p>
  <strong>Year:</strong>
  <%= @query.year %>
</p>

<p>
  <strong>Session:</strong>
  <%= @query.session %>
</p>

<p>
  <strong>Board:</strong>
  <%= @query.board %>
</p>

<p>
  <strong>Description:</strong>
  <%= @query.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @query.image.url %>
</p>

<p>
  <strong> Creator: </strong>
  <%= link_to @creator.name, @creator %>
  
</p>

<h3> Owner: <%= link_to "#{@query.profile.name}", @query.profile%> </h3>

<% if @query.profile_id == current_user.profile_id %> 

<%= link_to 'Submit Video', archive_query_path(@query) %> |

<%= link_to 'Edit', edit_query_path(@query) %> |
<% end %>
<%= link_to 'Back', portal_path %>